### ISSUE TITLE
table 选中高亮

### ISSUE THREAD

**Issue by chengfei2994** [xuliangzhan/vxe-table#177]
之前我加了样式：
 .vxe-table.row--highlight .vxe-body--row.row--current {
        background-color: #009def;
    }

这样是可以实现，后来我重新npm install之后估计更新了版本就失效了，目前用的是你给我的2.0.0-beta.15

谢谢

**Comment by xuliangzhan** [comment]
优先级的问题，你得看下你的样式和组件的引用顺序，或者再加一层
```css
.vxe-table.row--highlight .vxe-table--body .vxe-body--row.row--current {
  background-color: #009def;
}
```
