### ISSUE TITLE
table设置百分比高度时未能正确固定表头

### ISSUE THREAD

**Issue by natee** [xuliangzhan/vxe-table#262]
### （必填）填写问题描述 Describe the bug

**【version 2.3.2版本无此问题】**

table父元素为`flex:1`，给table设置百分比100%时，未能正确固定表头。
当给父容器设置`height`为**任意值**时，则可以固定表头

```css
.flex{
  padding: 20px;
  box-sizing:border-box;
  display:flex;
  flex-direction:column;
  position:absolute;
  left:0;
  top:0;
  right:0;
  bottom:0;
}
.flex-top:{
  height:60px;
  background:#eee;
}
.flex-content{
  flex:1;
  /* height:10px; */ // 父容器没有height（任意值）属性，表格无法正确计算高度
}
```

```html
<div class="flex">
  <p class="flex-top">height 100%不生效,无法固定表头</p>
  <div class="flex-content">
    <vxe-table height="100%" :data.sync="tableData"></vxe-table>
</div>
```

### （必填）填写能重现问题的链接 Reproduction link

 [jsrun](http://jsrun.pro/HEbKp/edit)

### 填写报错信息或截图 Error message or screenshots

![image](https://user-images.githubusercontent.com/4928035/63405940-fa5b6c00-c41a-11e9-84d7-544e8d0835ac.png)

### （必填）填写期望的结果 Expected behavior

 表格设置百分比高度可以正确固定表头

### （必填）版本 Version

- os: mac 10.14
- browser: chrome 75.0.3770.142
- vue: 2.6.10
- vxe-table: 2.3.4
